import { KeyInterface } from "./key";

// Width values use flex-based sizing for perfect row alignment.
// Standard 1u key = flex-1. Wider keys use flex-[Xu] where X is the unit multiplier.
// All rows automatically stretch to equal total width via CSS flex layout.

export const keys: KeyInterface[][] = [
  // --- ROW 1: Numbers — backtick(1u) + 12 keys(1u) + backspace(2u) = 15u ---
  [
    {
      label: "`",
      smallLabel: "`",
      capitalLabel: "`",
      shiftLabel: "~",
      specialLabel: "¬",
      capitalSpecialLabel: "¦",
      value: "`",
      type: "number",
    },
    {
      label: "1",
      smallLabel: "1",
      capitalLabel: "1",
      shiftLabel: "!",
      specialLabel: "¹",
      capitalSpecialLabel: "¡",
      value: "1",
      type: "number",
    },
    {
      label: "2",
      smallLabel: "2",
      capitalLabel: "2",
      shiftLabel: "@",
      specialLabel: "²",
      capitalSpecialLabel: "⅛",
      value: "2",
      type: "number",
    },
    {
      label: "3",
      smallLabel: "3",
      capitalLabel: "3",
      shiftLabel: "#",
      specialLabel: "³",
      capitalSpecialLabel: "£",
      value: "3",
      type: "number",
    },
    {
      label: "4",
      smallLabel: "4",
      capitalLabel: "4",
      shiftLabel: "$",
      specialLabel: "¢",
      capitalSpecialLabel: "¼",
      value: "4",
      type: "number",
    },
    {
      label: "5",
      smallLabel: "5",
      capitalLabel: "5",
      shiftLabel: "%",
      specialLabel: "‰",
      capitalSpecialLabel: "½",
      value: "5",
      type: "number",
    },
    {
      label: "6",
      smallLabel: "6",
      capitalLabel: "6",
      shiftLabel: "^",
      specialLabel: "∞",
      capitalSpecialLabel: "¾",
      value: "6",
      type: "number",
    },
    {
      label: "7",
      smallLabel: "7",
      capitalLabel: "7",
      shiftLabel: "&",
      specialLabel: "\\",
      capitalSpecialLabel: "{",
      value: "7",
      type: "number",
    },
    {
      label: "8",
      smallLabel: "8",
      capitalLabel: "8",
      shiftLabel: "*",
      specialLabel: "•",
      capitalSpecialLabel: "[",
      value: "8",
      type: "number",
    },
    {
      label: "9",
      smallLabel: "9",
      capitalLabel: "9",
      shiftLabel: "(",
      specialLabel: "±",
      capitalSpecialLabel: "]",
      value: "9",
      type: "number",
    },
    {
      label: "0",
      smallLabel: "0",
      capitalLabel: "0",
      shiftLabel: ")",
      specialLabel: "≠",
      capitalSpecialLabel: "}",
      value: "0",
      type: "number",
    },
    {
      label: "-",
      smallLabel: "-",
      capitalLabel: "-",
      shiftLabel: "_",
      specialLabel: "–",
      capitalSpecialLabel: "—",
      value: "-",
      type: "number",
    },
    {
      label: "=",
      smallLabel: "=",
      capitalLabel: "=",
      shiftLabel: "+",
      specialLabel: "≈",
      capitalSpecialLabel: "≡",
      value: "=",
      type: "number",
    },
    {
      label: "←",
      smallLabel: "Backspace",
      capitalLabel: "Backspace",
      value: "Backspace",
      width: "flex-[2]",
      type: "backspace",
    },
  ],
  // --- ROW 2: QWERTY — tab(1.5u) + 12 keys(1u) + backslash(1.5u) = 15u ---
  [
    {
      label: "Tab",
      smallLabel: "Tab",
      capitalLabel: "Tab",
      value: "Tab",
      width: "flex-[1.5]",
      type: "tab",
    },
    {
      label: "q",
      smallLabel: "q",
      capitalLabel: "Q",
      specialLabel: "œ",
      capitalSpecialLabel: "Œ",
      value: "q",
      type: "letter",
    },
    {
      label: "w",
      smallLabel: "w",
      capitalLabel: "W",
      specialLabel: "ω",
      capitalSpecialLabel: "Ω",
      value: "w",
      type: "letter",
    },
    {
      label: "e",
      smallLabel: "e",
      capitalLabel: "E",
      specialLabel: "€",
      capitalSpecialLabel: "È",
      value: "e",
      type: "letter",
    },
    {
      label: "r",
      smallLabel: "r",
      capitalLabel: "R",
      specialLabel: "₹",
      capitalSpecialLabel: "®",
      value: "r",
      type: "letter",
    },
    {
      label: "t",
      smallLabel: "t",
      capitalLabel: "T",
      specialLabel: "™",
      capitalSpecialLabel: "Þ",
      value: "t",
      type: "letter",
    },
    {
      label: "y",
      smallLabel: "y",
      capitalLabel: "Y",
      specialLabel: "¥",
      capitalSpecialLabel: "Ψ",
      value: "y",
      type: "letter",
    },
    {
      label: "u",
      smallLabel: "u",
      capitalLabel: "U",
      specialLabel: "ü",
      capitalSpecialLabel: "Ü",
      value: "u",
      type: "letter",
    },
    {
      label: "i",
      smallLabel: "i",
      capitalLabel: "I",
      specialLabel: "í",
      capitalSpecialLabel: "Í",
      value: "i",
      type: "letter",
    },
    {
      label: "o",
      smallLabel: "o",
      capitalLabel: "O",
      specialLabel: "ö",
      capitalSpecialLabel: "Ö",
      value: "o",
      type: "letter",
    },
    {
      label: "p",
      smallLabel: "p",
      capitalLabel: "P",
      specialLabel: "π",
      capitalSpecialLabel: "Π",
      value: "p",
      type: "letter",
    },
    {
      label: "[",
      smallLabel: "[",
      capitalLabel: "[",
      shiftLabel: "{",
      specialLabel: "„",
      capitalSpecialLabel: "\u201C",
      value: "[",
      type: "special",
    },
    {
      label: "]",
      smallLabel: "]",
      capitalLabel: "]",
      shiftLabel: "}",
      specialLabel: "\u201D",
      capitalSpecialLabel: "\u201D",
      value: "]",
      type: "special",
    },
    {
      label: "\\",
      smallLabel: "\\",
      capitalLabel: "\\",
      shiftLabel: "|",
      specialLabel: "«",
      capitalSpecialLabel: "»",
      value: "\\",
      type: "special",
      width: "flex-[1.5]",
    },
  ],
  // --- ROW 3: ASDF — caps(1.75u) + 11 keys(1u) + enter(2.25u) = 15u ---
  [
    {
      label: "Caps",
      smallLabel: "Caps Lock",
      capitalLabel: "Caps Lock",
      value: "CapsLock",
      width: "flex-[1.75]",
      type: "caps",
    },
    {
      label: "a",
      smallLabel: "a",
      capitalLabel: "A",
      specialLabel: "ä",
      capitalSpecialLabel: "Ä",
      value: "a",
      type: "letter",
    },
    {
      label: "s",
      smallLabel: "s",
      capitalLabel: "S",
      specialLabel: "ß",
      capitalSpecialLabel: "ẞ",
      value: "s",
      type: "letter",
    },
    {
      label: "d",
      smallLabel: "d",
      capitalLabel: "D",
      specialLabel: "°",
      capitalSpecialLabel: "Δ",
      value: "d",
      type: "letter",
    },
    {
      label: "f",
      smallLabel: "f",
      capitalLabel: "F",
      specialLabel: "ƒ",
      capitalSpecialLabel: "Φ",
      value: "f",
      type: "letter",
    },
    {
      label: "g",
      smallLabel: "g",
      capitalLabel: "G",
      specialLabel: "ĝ",
      capitalSpecialLabel: "Γ",
      value: "g",
      type: "letter",
    },
    {
      label: "h",
      smallLabel: "h",
      capitalLabel: "H",
      specialLabel: "ĥ",
      capitalSpecialLabel: "Ħ",
      value: "h",
      type: "letter",
    },
    {
      label: "j",
      smallLabel: "j",
      capitalLabel: "J",
      specialLabel: "ĵ",
      capitalSpecialLabel: "ϑ",
      value: "j",
      type: "letter",
    },
    {
      label: "k",
      smallLabel: "k",
      capitalLabel: "K",
      specialLabel: "ĸ",
      capitalSpecialLabel: "˚",
      value: "k",
      type: "letter",
    },
    {
      label: "l",
      smallLabel: "l",
      capitalLabel: "L",
      specialLabel: "ø",
      capitalSpecialLabel: "Ø",
      value: "l",
      type: "letter",
    },
    {
      label: ";",
      smallLabel: ";",
      capitalLabel: ";",
      shiftLabel: ":",
      specialLabel: "…",
      capitalSpecialLabel: "¶",
      value: ";",
      type: "special",
    },
    {
      label: "'",
      smallLabel: "'",
      capitalLabel: "'",
      shiftLabel: '"',
      specialLabel: "´",
      capitalSpecialLabel: "§",
      value: "'",
      type: "special",
    },
    {
      label: "Enter",
      smallLabel: "Enter",
      capitalLabel: "Enter",
      value: "Enter",
      width: "flex-[2.25]",
      type: "enter",
    },
  ],
  // --- ROW 4: ZXCV — LShift(2.25u) + 10 keys(1u) + RShift(2.75u) = 15u ---
  [
    {
      label: "Shift",
      smallLabel: "Shift",
      capitalLabel: "Shift",
      value: "Shift",
      width: "flex-[2.25]",
      type: "shift",
      code: "ShiftLeft",
    },
    {
      label: "z",
      smallLabel: "z",
      capitalLabel: "Z",
      specialLabel: "æ",
      capitalSpecialLabel: "Æ",
      value: "z",
      type: "letter",
    },
    {
      label: "x",
      smallLabel: "x",
      capitalLabel: "X",
      specialLabel: "×",
      capitalSpecialLabel: "Ξ",
      value: "x",
      type: "letter",
    },
    {
      label: "c",
      smallLabel: "c",
      capitalLabel: "C",
      specialLabel: "©",
      capitalSpecialLabel: "Ç",
      value: "c",
      type: "letter",
    },
    {
      label: "v",
      smallLabel: "v",
      capitalLabel: "V",
      specialLabel: "√",
      capitalSpecialLabel: "◊",
      value: "v",
      type: "letter",
    },
    {
      label: "b",
      smallLabel: "b",
      capitalLabel: "B",
      specialLabel: "∫",
      capitalSpecialLabel: "ß",
      value: "b",
      type: "letter",
    },
    {
      label: "n",
      smallLabel: "n",
      capitalLabel: "N",
      specialLabel: "ñ",
      capitalSpecialLabel: "Ñ",
      value: "n",
      type: "letter",
    },
    {
      label: "m",
      smallLabel: "m",
      capitalLabel: "M",
      specialLabel: "µ",
      capitalSpecialLabel: "M",
      value: "m",
      type: "letter",
    },
    {
      label: ",",
      smallLabel: ",",
      capitalLabel: ",",
      shiftLabel: "<",
      specialLabel: "≤",
      capitalSpecialLabel: "«",
      value: ",",
      type: "special",
    },
    {
      label: ".",
      smallLabel: ".",
      capitalLabel: ".",
      shiftLabel: ">",
      specialLabel: "≥",
      capitalSpecialLabel: "»",
      value: ".",
      type: "special",
    },
    {
      label: "/",
      smallLabel: "/",
      capitalLabel: "/",
      shiftLabel: "?",
      specialLabel: "÷",
      capitalSpecialLabel: "¿",
      value: "/",
      type: "special",
    },
    {
      label: "Shift",
      smallLabel: "Shift",
      capitalLabel: "Shift",
      value: "Shift",
      width: "flex-[2.75]",
      type: "shift",
      code: "ShiftRight",
    },
  ],
  // --- ROW 5: Bottom — Windows ANSI: Ctrl+Win+Alt+Space+Alt+Win+Menu+Ctrl = 15u ---
  [
    {
      label: "Ctrl",
      smallLabel: "Ctrl",
      capitalLabel: "Ctrl",
      value: "Control",
      width: "flex-[1.25]",
      type: "ctrl",
      code: "ControlLeft",
    },
    {
      label: "Win",
      smallLabel: "Win",
      capitalLabel: "Win",
      value: "Meta",
      width: "flex-[1.25]",
      type: "win",
      code: "MetaLeft",
    },
    {
      label: "Alt",
      smallLabel: "Alt",
      capitalLabel: "Alt",
      value: "Alt",
      width: "flex-[1.25]",
      type: "alt",
      code: "AltLeft",
    },
    {
      label: "Space",
      smallLabel: " ",
      capitalLabel: " ",
      value: " ",
      width: "flex-[6.25]",
      type: "space",
      code: "Space",
    },
    {
      label: "Alt",
      smallLabel: "Alt",
      capitalLabel: "Alt",
      value: "Alt",
      width: "flex-[1.25]",
      type: "alt",
      code: "AltRight",
    },
    {
      label: "Win",
      smallLabel: "Win",
      capitalLabel: "Win",
      value: "Meta",
      width: "flex-[1.25]",
      type: "win",
      code: "MetaRight",
    },
    {
      label: "Fn",
      smallLabel: "Fn",
      capitalLabel: "Fn",
      value: "Fn",
      width: "flex-[1.25]",
      type: "win",
      code: "Fn",
    },
    {
      label: "Ctrl",
      smallLabel: "Ctrl",
      capitalLabel: "Ctrl",
      value: "Control",
      width: "flex-[1.25]",
      type: "ctrl",
      code: "ControlRight",
    },
  ],
] as const;
